version: '3.4'
services:
#  Optional
#  metadatawriter-share:
#    image: ${docker.share.image}:${alfresco.share.version}
#    environment:
#      REPO_HOST: metadatawriter-acs
#      REPO_PORT: 8080
#    ports:
#      - "${share.port}:8080"
  metadatawriter-acs:
    image: alfresco-content-services-metadatawriter:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    command: ["catalina.sh", "run"]
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - metadatawriter-acs-volume:/usr/local/tomcat/alf_data
      - ../../../target/classes:/usr/local/tomcat/hotswap-agent/metadatawriter/target/classes
      - ../../../target/test-classes:/usr/local/tomcat/hotswap-agent/metadatawriter/target/test-classes
    depends_on:
      - metadatawriter-postgres
  metadatawriter-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - metadatawriter-db-volume:/var/lib/postgresql/data
  metadatawriter-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: metadatawriter-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: metadatawriter-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - metadatawriter-ass-volume:/opt/alfresco-search-services/contentstore
      - metadatawriter-ass-volume:/opt/alfresco-search-services/data
volumes:
  metadatawriter-acs-volume:
    external: true
  metadatawriter-db-volume:
    external: true
  metadatawriter-ass-volume:
    external: true